server:
  port: 8080
spring:
  kafka:
    listener:
      missing-topics-fatal: false
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.tk.practice.ics.controller.kafka.serializer.UserSerializer
